django_001/accounts/urls.py
# accounts/urls.py

from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

django_001/articles/urls.py
# articles/urls.py

from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
    
]

django_001/django_001/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),

]

django_001/accounts/models.py
# accounts/models.py

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

django_001/articles/models.py
# articles/models.py 

from django.db import models

# Create your models here.
class Article(models.Model):
  # id 필드는 자동 생성
  title = models.CharField(max_length=10)
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

django_001/accounts/views.py
# accounts/views.py

from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm


# Create your views here.
def index(request):
    return render(request, 'index.html')

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context ={
        'form': form,
    }
    return render(request, 'login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('articles:index')

django_001/articles/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'index.html')

def new(request):
    return render(request, 'new.html')

django_001/articles/templates/index.html
<!-- articles/index.html-->

{% extends 'base.html' %}

{% block title %}
<title>Articles</title>
{% endblock title %}

{% block content %}
<h3>hello, {{ user }}<h3>
<h1>Articles<h1>
{% if user.is_authenticated %}
  <a href={% url 'accounts:logout' %}>LogOut</a>
{% else %}
  <a href={% url 'accounts:login' %}>LogIn</a>
{% endif %}
<a href={% url 'articles:new' %}>NEW</a>
  
{% endblock content %}

django_001/articles/templates/new.html
<!--articles/new.html-->

{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block content %}
<h3>New Article</h3>
{% endblock content %}

django_001/articles/templates/skeleton.html
<!--skeletion.html-->

{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block content %}
{% endblock content %}