django_003/albums/urls.py
# albums/urls.py

from django.urls import path
from . import views


app_name = 'albums'

urlpatterns = [
    path('', views.index, name='index'),
   
]

django_003/django_003/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_003/albums/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    content = models.CharField(max_length = 20)

    # MEDIA_ROOT 이후의 추가 경로를 설정 => upload_to
    image = models.ImageField(blank=True, upload_to='uploaded')


# 필드 이름	역할	django 필드	속성
# content	내용	Char	max_length=20
# image	이미지	Image	blank=True, upload_to='임의 경로'

django_003/albums/forms.py
# albums/forms.py

from django import forms
from .models import Album


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = '__all__'

django_003/albums/views.py
from django.shortcuts import render, redirect
from .models import Album
from .forms import AlbumForm


# Create your views here.
def index(request):
    
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES)
        form.save()
    else:
        pass
    context = {
        'albums': Album.objects.all(),
        'form': AlbumForm(),
    }

    return render(request, 'albums/index.html', context)

django_003/albums/templates/albums/index.html
<!--index.html-->

{% extends 'base.html' %}

{% block title %}
My Album
{% endblock title %}


{% block nav %}
  {% load static %}
  <nav class="navbar navbar-expand-md">
    <div class="container-fluid d-flex flex-row">
      <div class="container d-flex flex-row" id="nav_logo_box">
        <div class="image_wrapper" style="width:100px;">
          <img src="{% static 'albums/logo.jpeg' %}" class="img-fluid" alt="album_logo">
        </div>
        <div class="container-fluid text_wrapper">
          <p class="fs-2 align-text-bottom">My Album</p>
      </div>
      <div class="container" id="nav_btn_box">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
          이미지 공유
        </button>
      </div>
    </div>
  </nav>
{% endblock nav %}

{% block content %}
  {% load static %}

  <div class="container">
    
    <div class="row g-2 row-cols-1 row-cols-sm-2 row-cols-md-4 align-items-start">


      {% for album in albums %}
      <div class="col">
        <img src="{{ album.image.url }}" class="rounded img-fluid" alt="img">
      </div>
      {% endfor %}


    </div>
  </div>
{% endblock content %}


{% block modal %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">이미지 업로드 </h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>이미지를 업로드 하세요 </p>
        <form action="{% url 'albums:index' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit">
        </form>
        

    </div>
  </div>
</div> 
{% endblock modal %}

django_003/templates/base copy.html
<!--*.html-->

{% extends 'base.html' %}

{% block content %}

{% load static %}

{% endblock content %}
  
  

django_003/templates/base.html
<!--base.html-->


<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>{% block title %}{% endblock title %}</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    {% comment %} <link href="customstyle.css" rel="stylesheet"> {% endcomment %}

  </head>
  <body>
    
    <div class="container d-flex flex-column">

      {% block nav %}

      {% endblock nav %}
    
        
      {% block content %}
      {% endblock content %}
  

      {% block modal %}
      {% endblock modal %}
  
      {% block footer %}
      {% endblock footer %}


  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
  </body>
</html>