pair_001_accountbooks/accountbooks/urls.py
from django.urls import path
from . import views

app_name="accountbooks"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:account_book_pk>/', views.detail, name="detail"),
    path('new/', views.create, name="create"),
]   

pair_001_accountbooks/accountbooks/models.py
from django.db import models

# Create your models here.
class AccountBook(models.Model):
    CATEGORY = [
        ("01", "수입"), 
        ("02", "지출"), 
    ]
    
    note = models.CharField(max_length=80) # 내용	
    description = models.TextField(null=True) #	메모
    category = models.CharField(max_length=20, choices=CATEGORY) # 분류
    amount = models.IntegerField(default=0) # 사용 금액
    date = models.DateField() # 사용 날짜	
    created_at = models.DateTimeField(auto_now_add=True) # 생성 날짜
    updated_at = models.DateTimeField(auto_now=True) # 수정 날짜


class LineItem(models.Model):
    DEBIT_OR_CREDIT = [
    ("C", "Credit"),
    ("D", "Debit"),
    ]
    date = models.DateField()
    amount = models.IntegerField(default=0)
    note = models.CharField(max_length=80)
    debit_credit = models.CharField(max_length=1, choices=DEBIT_OR_CREDIT)

pair_001_accountbooks/accountbooks/forms.py
from django.forms import ModelForm, Form
from .models import AccountBook

class LineItemForm(ModelForm):
    class Meta:
        model = AccountBook
        fields = ('date', 'amount', )

pair_001_accountbooks/accountbooks/views.py
from django.shortcuts import render, redirect
from .models import AccountBook

# Create your views here.
def index(request):
    context = {
        'accountbooks': AccountBook.objects.all().order_by('-date')
    }
    return render(request, 'accountbooks/index.html', context)

def detail(request, account_book_pk):
    item = AccountBook.objects.get(pk=account_book_pk)
    return render(request, 'accountbooks/detail.html', {'item':item})

def create(request):
    if request.method == "POST":
        AccountBook.objects.create(note=request.POST['note'], category=request.POST['category'], date=request.POST['date'])
        return redirect('accountbooks:index')
    else:
        context = {
            'category_list': AccountBook.CATEGORY
        }
        return render(request, 'accountbooks/create.html', context)

pair_001_accountbooks/accountbooks/templates/accountbooks/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% for i in range(10) %}
{% include 'create_form.html' %}
{% endfor %}

{% endblock content %}

pair_001_accountbooks/accountbooks/templates/accountbooks/create_form.html
<form action="{% url 'accountbooks:create' %}" method="post">
  {% csrf_token %}
  <table>
    <tr>
      <select name="category" id="category">
        {% for code, category in category_list %}
        <option value="{{ code }}">{{ category }}</option>
        {% endfor %}
      </select>
      <input type="date" name="date" id="date" value="{% now "Y-m-d" %}" placeholder="{% now "Y-m-d" %}">
      <input type="number" name="amount" id="amount" placeholder="amount">
      <input type="text" name="note" id="note" placeholder="note">
      <input type="text" name="description" id="description" placeholder="description">
      <input type="submit" value="save">
    </tr>
  </table>
</form>

pair_001_accountbooks/accountbooks/templates/accountbooks/detail.html
{% extends 'base.html' %}

{% block content %}
<p>{{ item.date }}</p>
<p>{{ item.amount }} </p>
<p>{{ item.note }}</p>
<p>{{ item.descripton }}</p>
<form action="#" method="GET">
  <input type="submit" value="수정">
</form>
<form action="#" method="POST">
  <input type="submit" value="삭제">
</form>
<form action="#" method="POST">
  <input type="submit" value="복사">
</form>
{% endblock content %}

pair_001_accountbooks/accountbooks/templates/accountbooks/index.html
{% extends 'base.html' %}

{% block content %}
<h1>INDEX - 당신의 가계부</h1>
<a href="{% url 'accountbooks:create' %}">new item</a>
{% for lineitem in accountbooks %}
<p><a href="{% url 'accountbooks:detail' lineitem.pk %}">{{ lineitem.date|date:"m/d" }} {{ lineitem.amount }} {{ lineitem.note }}</a></p>
{% endfor %}
{% endblock content %}