django_002/django_002/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

django_002/posts/urls.py
# posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/edit/', views.edit, name='edit'),
    path('<int:post_pk>/delete/', views.delete, name='delete'), 
    path('<int:post_pk>/update/', views.update, name='update'), 
]

django_002/posts/models.py
# posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    DEVELOPMENT = 'DEV'
    COMPUTER_SCIENCE = 'CS'
    NEW_TECHNOLOGY = 'NEW_TECH'
    CATEGORY = [
        (DEVELOPMENT, '개발'),
        (COMPUTER_SCIENCE, 'CS'),
        (NEW_TECHNOLOGY, '신기술'),
    ]

    title = models.CharField(max_length=80)
    content = models.TextField(null=False)
    category = models.CharField(
        max_length=20, choices=CATEGORY, default=DEVELOPMENT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_categories():
        DEVELOPMENT = 'DEV'
        COMPUTER_SCIENCE = 'CS'
        NEW_TECHNOLOGY = 'NEW_TECH'
        CATEGORY = [
            (DEVELOPMENT, '개발'),
            (COMPUTER_SCIENCE, 'CS'),
            (NEW_TECHNOLOGY, '신기술'),
        ]
        categories = [item[0] for item in CATEGORY]
        return categories

django_002/posts/forms.py
# posts/forms.py

# 폼 이름 : PostForm
# 폼 모델 : Post
# 입력 필드
# title
# content
# category

from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'category',)

django_002/posts/views.py
# posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import PostForm
from .models import Post

# Create your views here.


def index(request):
    posts = Post.objects.all()
    CATEGORY = Post.CATEGORY

    if request.method == "GET":
        posts = Post.objects.filter(category=request.GET.get("category"))
    context = {
        'posts': posts,
        'categories': Post.get_categories()
    }
    return render(request, 'posts/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/create.html', context)


def edit(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    form = PostForm(instance=post)
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/edit.html', context)


def detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    context = {
        'post': post,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    post.delete()
    return redirect('posts:index')


@login_required
def update(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    post.title = request.POST.get('title')
    post.content = request.POST.get('content')
    post.category = request.POST.get('category')
    post.save()
    return redirect('posts:detail', post.pk)

django_002/posts/templates/posts/create.html
<!--posts/index.html-->

{% extends 'base.html' %}

{% block content %}

<h1>NEW</h1>
<form action="{% url 'posts:create' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>

{% endblock content %}

django_002/posts/templates/posts/detail.html
<!--posts/index.html-->

{% extends 'base.html' %}

{% block content %}

<p>글 번호 - {{ post.pk }}</p>
<p>글 제목 - {{ post.title }}</p>
<p>글 내용 - {{ post.content }}</p>
<p>글 카테고리 - {{ post.category }}</p>
<a href="{% url 'posts:edit' post.pk %}">EDIT</a><br>
<form action= "{% url 'posts:delete' post.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
</form>
<a href={% url 'posts:index' %}>BACK</a>

{% endblock content %}

django_002/posts/templates/posts/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>EDIT</h1>

  <form action="{% url 'posts:update' post.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>

{% endblock content %}

django_002/posts/templates/posts/index.html
<!--posts/index.html-->

{% extends 'base.html' %}

{% block content %}
<content>
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">글 번호</th>
          <th scope="col">카테고리</th>
          <th scope="col">작성자</th>
        </tr>
      </thead>
      <tbody>
      {% for post in posts %}
      <tr>
        <th scope="row">{{ post.pk }}</th>
        <td>{{ post.category }}</td>
        <td>{{ post.title }}</td>
        <td>[차후 추가 작성자</td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
  </div>
</content>

{% endblock content %}